repos:
-   hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--allow-multiple-documents]
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
# -   hooks:
#     -   id: check-json5
#     repo: https://gitlab.com/bmares/check-json5
#     rev: v1.0.0
-   hooks:
    -   id: gitleaks
    repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        args: [--line-length, "200"]
-   repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: [--line-length, "200"]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args: [--max-line-length=200]
