# @copyright 2024 Retlek Systems Inc.

name: Lint DockerFiles
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - docker/**
      - .github/workflows/lint_docker.yml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Lint Dockerfile(s)
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: |
            ./docker/sw-dev/Dockerfile
            ./docker/sw-aarch64-linux-gnu/Dockerfile
            ./docker/sw-arm-none-eabi/Dockerfile
            ./docker/hw-dev/Dockerfile
            ./docker/hw-backend/Dockerfile
            ./docker/docs/Dockerfile
