# @copyright 2024 Retlek Systems Inc.

name: Publish to Docker
on:
  release:
    types: 
      - published

env:
  REGISTRY: ghcr.io
 
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Extract repo name and version from release tag
        id: info
        run: |
          echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          REPO_NAME_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "image_name=$REPO_NAME_LOWER" >> $GITHUB_OUTPUT
      # --------------------
      # SW Dev Container
      - name: Build sw-dev container
        uses: docker/build-push-action@v5
        with:
          context: ./docker/sw-dev
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/sw-dev:${{ steps.info.outputs.version }}
            ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/sw-dev:latest
      - name: Inspect sw-dev docker image
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/sw-dev:${{ steps.info.outputs.version }}
      # --------------------
      # HW Dev Container - relies on SW Dev container
      - name: Build hw-dev container
        uses: docker/build-push-action@v5
        with:
          context: ./docker/hw-dev
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/hw-dev:${{ steps.info.outputs.version }}
            ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/hw-dev:latest
      - name: Inspect hw-dev docker image
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/hw-dev:${{ steps.info.outputs.version }}
      # --------------------
      # Doc Container - relies on SW Dev container
      - name: Build docs container
        uses: docker/build-push-action@v5
        with:
          context: ./docker/docs
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/docs:${{ steps.info.outputs.version }}
            ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/docs:latest
      - name: Inspect docs docker image
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/docs:${{ steps.info.outputs.version }}
      # --------------------
      # HW Backend Container - relies on SW Dev container
      - name: Build hw-backend container
        uses: docker/build-push-action@v5
        with:
          context: ./docker/hw-backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/hw-backend:${{ steps.info.outputs.version }}
            ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/hw-backend:latest
      - name: Inspect hw-backend docker image
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.info.outputs.image_name }}/hw-backend:${{ steps.info.outputs.version }}
