# @copyright 2024 Retlek Systems Inc.

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(TOOLCHAIN_TRIPPLE aarch64-linux-gnu)

set(CMAKE_LIBRARY_ARCHITECTURE ${TOOLCHAIN_TRIPPLE})

set(TOOLCHAIN_LOCATION "/usr")
set(TOOLCHAIN_PATH ${TOOLCHAIN_LOCATION} CACHE INTERNAL "Toolchain Location.")

set(TOOLCHAIN_BIN_DIR ${TOOLCHAIN_PATH}/bin)

find_program(TOOLCHAIN_C   NAMES ${TOOLCHAIN_TRIPPLE}-gcc
	PATHS ${TOOLCHAIN_BIN_DIR}
	DOC "${TOOLCHAIN_TRIPPLE} Toolchain C compiler executable" )
find_program(TOOLCHAIN_CXX NAMES ${TOOLCHAIN_TRIPPLE}-g++
    PATHS ${TOOLCHAIN_BIN_DIR}
    DOC "${TOOLCHAIN_TRIPPLE} Toolchain CXX compiler executable" )
find_program(TOOLCHAIN_AR NAMES ${TOOLCHAIN_TRIPPLE}-ar
    PATHS ${TOOLCHAIN_BIN_DIR}
    DOC "${TOOLCHAIN_TRIPPLE} Toolchain AR executable" )
find_program(TOOLCHAIN_RANLIB NAMES ${TOOLCHAIN_TRIPPLE}-ranlib
    PATHS ${TOOLCHAIN_BIN_DIR}
    DOC "${TOOLCHAIN_TRIPPLE} Toolchain Ranlib executable" )
find_program(TOOLCHAIN_OBJCOPY   NAMES ${TOOLCHAIN_TRIPPLE}-objcopy
    PATHS ${TOOLCHAIN_BIN_DIR}
    DOC "${TOOLCHAIN_TRIPPLE} Toolchain Object copy executable" )
find_program(TOOLCHAIN_SIZE_TOOL NAMES ${TOOLCHAIN_TRIPPLE}-size
    PATHS ${TOOLCHAIN_BIN_DIR}
    DOC "${TOOLCHAIN_TRIPPLE} Toolchain size tool executable" )

set(CMAKE_C_COMPILER   ${TOOLCHAIN_C})
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_C})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_CXX})
set(CMAKE_AR           ${TOOLCHAIN_AR})
set(CMAKE_RANLIB       ${TOOLCHAIN_RANLIB})
set(CMAKE_LINKER       ${TOOLCHAIN_C})
set(CMAKE_OBJCOPY      ${TOOLCHAIN_OBJCOPY}   CACHE INTERNAL "Toolchain Object Copy tool")
set(CMAKE_SIZE_TOOL    ${TOOLCHAIN_SIZE_TOOL} CACHE INTERNAL "Toolchain Size Tool")


SET(CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_PATH}/${TOOLCHAIN_TRIPPLE}" )
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_CROSSCOMPILING_EMULATOR /usr/bin/qemu-aarch64-static)
