# @copyright 2021 Retlek Systems Inc.

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(TOOLCHAIN_TRIPPLE aarch64-linux-gnu)

set(CMAKE_LIBRARY_ARCHITECTURE ${TOOLCHAIN_TRIPPLE})

# Assuming toolchain installed in /usr/
if (NOT DEFINED $ENV{JETSON_SYSROOT})
    set(JETSON_SYSROOT "/home/$ENV{USER}/nvidia/nvidia_sdk/JetPack_4.6_Linux_JETSON_AGX_XAVIER_TARGETS/Linux_for_Tegra/rootfs/")
else()
    set(JETSON_SYSROOT $ENV{JETSON_SYSROOT})
endif()
set(LINARO_PATH "/usr/local/gcc-linaro-7.3.1-2018.05-x86_64_${TOOLCHAIN_TRIPPLE}")

set(CMAKE_SYSROOT ${JETSON_SYSROOT})
set(CMAKE_C_COMPILER ${LINARO_PATH}/bin/${TOOLCHAIN_TRIPPLE}-gcc)
set(CMAKE_CXX_COMPILER ${LINARO_PATH}/bin/${TOOLCHAIN_TRIPPLE}-g++)

#set(CMAKE_C_FLAGS_INIT   "-B${TOOLCHAIN_DIR}")
#set(CMAKE_CXX_FLAGS_INIT "-B${TOOLCHAIN_DIR}")

SET(CMAKE_FIND_ROOT_PATH ${JETSON_SYSROOT} )
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_CROSSCOMPILING_EMULATOR /usr/bin/qemu-aarch64-static)